### ISSUE TITLE
adding a --target option to partially polishing a genome

### ISSUE THREAD

**Issue by chklopp** [bcgsc/ntEdit#13]
I order to run ntEdit in parallel on multiple cluster nodes could you add a --target option similar to the one found in pilon.

[pilon options](https://github.com/broadinstitute/pilon/wiki/Requirements-&-Usage)

   --targets targetlist
          Only process the specified target(s).  Targets are comma-separated, and each target
          is a fasta element name optionally followed by a base range.
          Example: "scaffold00001,scaffold00002:10000-20000" would result in processing all of
          scaffold00001 and coordinates 10000-20000 of scaffold00002.
          If "targetlist" is the name of a file, each line will be treated as a target
          specification.

**Comment by warrenlr** [comment]
thank you for the request.  

not too sure what would be the advantage of targeted polishing since whole genome sequences can be polished quite fast without the need for embarrassingly parallel methods (ntedit employs thread-level parallelism).
