### ISSUE TITLE
Can ntEdit remove haplotype redundance?

### ISSUE THREAD

**Issue by xiekunwhy** [bcgsc/ntEdit#15]
Hi,

"ntEdit simplifies polishing and haploidization", what haploidization means here, can ntEdit use for haplotype redundance removing, I used wtdgb2 to assemble a high heterozygous rate(may be >1.5%) plant genome, the expected genome size is ~3.2G, but I got ~4.1G assembly sequence, too many haplotype redundance there, may be. So I want to find some tools to remove the redundances.

Best wishes,
Kun

**Comment by warrenlr** [comment]
hi Kun,

thank you for your message.  ntEdit is not the tool you are looking for.  

It is a sequence assembly polishing tool, and as described in our manuscript can be use to turn a pseudohaploid genome assembly into it's haploid counterpart (if you have a haploid tissue source, like seeds). We now also support SNV reporting but it does not collapse haplotype redundancy.

**Comment by lcoombe** [comment]
Hi Kun,
Another suggestion for a tool to remove redundancy due to high heterozygosity is purge_haplotigs.

**Comment by xiekunwhy** [comment]
Hi Rene,
I will try purge_haplotigs and some other tools.
Thank you for your suggestion.
Best,
Kun
