### ISSUE TITLE
Short variant detection with --genome option

### ISSUE THREAD

**Issue by asan-emirsaleh** [bcgsc/ntEdit#56]
Hello!
Really good tool. Documentation is great too. But one thing is still not clear for me after I read it. What are the preferred options to perform short variant detection between two assemblies of the same genome or genomes of two close-related species?
I suppose them be
`run-ntedit snv  --reference <ref.fna> --genome <assembly2.fna> -k 55 --cutoff 1`
Is it right? What is your suggestion?

**Comment by warrenlr** [comment]
Your command is correct. Note, for a higher precision, you may wish to set -j 1 -Y 1
Thank you for your interest in ntedit!
