### ISSUE TITLE
third-generation assembly

### ISSUE THREAD

**Issue by gorliver** [bcgsc/ntEdit#6]
Hi,
Can ntEdit be used to polish pacbio or nanopore assembly?

gorliver

**Comment by warrenlr** [comment]
Absolutely!  I invite you to read our publication https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz400/5490204

particularly the bit on single molecule sequence (SMS) assemblies of NA12878 human "..experimental human NA12878 SMS assemblies..". Also consult supplemental table S8 for results/params. run on pacbio and nanopore assemblies.
