### ISSUE TITLE
why snakemake error showing up when executing polish workflow

### ISSUE THREAD

**Issue by akshaydinesh26** [bcgsc/ntEdit#65]
i was executing the code example given in the github page 

this is my code:
run-ntedit polish --draft filt_contig_assembly.fa --reads filtered_P1 -k 71 -t 8

but it is showing an error and based on my search its because of snakemake
run-ntedit polish --draft filt_contig_assembly.fa --reads filtered_P1 -k 71 -t 8
Running ntEdit...
Parameter settings:
	--draft filt_contig_assembly.fa
	--reads filtered_P1
	-k 71
	-t 8
	-z 100
	-y 9.0
	-j 3
	--cutoff 2
	-i 5
	-d 5
	-x 5.0
	-m 0
	-a 0
Running snakemake -s /home/centyle-biotech/miniconda3/envs/ntedit/bin/ntedit_run_pipeline.smk ntedit -p --cores 8 --config draft=filt_contig_assembly.fa k=71 t=8 z=100 y=9.0 v=False j=3 reads=filtered_P1 cutoff=2 v=0 i=5 d=5 x=5.0 m=0 a=0  --rerun-trigger mtime 
Traceback (most recent call last):

  File "/home/centyle-biotech/miniconda3/envs/ntedit/lib/python3.12/site-packages/snakemake/cli.py", line 1977, in args_to_api
    config=parse_config(args.config),
           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/centyle-biotech/miniconda3/envs/ntedit/lib/python3.12/site-packages/snakemake/cli.py", line 256, in parse_config
    raise ValueError(

ValueError: Invalid config definition: Config entry must start with a valid identifier.

Traceback (most recent call last):
  File "/home/centyle-biotech/miniconda3/envs/ntedit/bin/run-ntedit", line 248, in <module>
    main()
  File "/home/centyle-biotech/miniconda3/envs/ntedit/bin/run-ntedit", line 243, in main
    raise subprocess.SubprocessError("ntEdit failed - check the logs for the error.")
subprocess.SubprocessError: ntEdit failed - check the logs for the error.

**Comment by akshaydinesh26** [comment]
I reinstalled it with python version 3.9 and snakemak version 7.32.4 it worked.

**Comment by lcoombe** [comment]
Hi @akshaydinesh26,

Do you know which version of snakemake you were using before you changed the version?

Your error looks like this error which I previously reported upstream: https://github.com/snakemake/snakemake/issues/3015  

Thanks for your interest in ntEdit and for reporting which snakemake version worked for you!
Lauren

**Comment by lcoombe** [comment]
Fixes for snakemake 8.17.0+ completed in #66 and released in v2.0.3
