### ISSUE TITLE
Reg: polishing using Long-Reads

### ISSUE THREAD

**Issue by harish0201** [bcgsc/ntEdit#7]
Hi!

Thank you for this wonderful tool! I've been able to drop down the polishing time a lot and it's much easier to use as well.

I have a question, sometimes I do tend to work on projects for which data on Short Reads haven't been generated for whatever reason

Can I use the Long-Read datasets to polish the genome? Given that Pacbio has a random error profile, I think solid kmers shouldn't be impacted. 

Does it make sense intuitively?

**Comment by warrenlr** [comment]
it does make sense for pacbio, as long as there are no systematic errors & biases-- and that you have sufficient coverage from those long reads. I have never tried it, so please, do let me know how it goes!

I find BUSCO a very useful proxy for assessing how polishing impacts the assemblies globally.  You could run it pre and post ntEdit :)

**Comment by harish0201** [comment]
Hey!

Thanks for answering the question! I'm planning to try this in a while for a genome I'm assembling :)

I'll do a couple of test runs on E.coli to see if this thing works!

**Comment by warrenlr** [comment]
Which version are you using?  The latest v1.2.2 fixes the ballooning bug.. do let us know the version/k/param combos used where you’ve encountered. Thx

**Comment by harish0201** [comment]
Hi!

Apologies for not getting back earlier!

For the issues above, I have been using ntEdit v1.2.1, I installed the newer one today! (Big stupidity on my part :/ )

Generally the kmers I tend to use are either 40 or 50, I haven't played much with them, though based on a couple of runs in-house, I did get best run times and corrections at 40,50 and 60 tbh, because I tend to do a lot of repeat rich genomes that longer kmers are preferable.

Would you also have any suggestions on polishing highly heterozygous genomes? One of the insect that I'm working on has a 4% heterozygosity rate.

**Comment by warrenlr** [comment]
great, good to hear!

I suggest you run ntEdit iteratively by decreasing k values 60 > 50 > 40

About the high heterozygosity rate, not much you can do but use high k. Also, specificity in kmer mapping may be achieved by decreasing the y value (take a look at "Tuning" section here: https://warrenlr.github.io/papers/ntedit_ismb2019.pdf to help guide you)
